image: $IMAGE_REPOSITORY_URL/python:3.7

stages:
  - build

default:
  tags:
    - k8s-small-generic

lint:
  stage: build
  before_script:
    - pip install flake8
  script:
    - flake8 data-generator/
    - flake8 exercises/viz.py